# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  apt_packages:
    - libmagic-dev
    - libmagic1
  tools:
    python: "3.10"
  jobs:
    post_checkout:
      - git fetch --tags || true

sphinx:
  configuration: doc/conf.py

formats: all

python:
   install:
   - requirements: requirements-docs.txt
