version: "3"

volumes:
  ckan_storage:
  pg_data:
  solr_data:
networks:
  monolito: {}     

services:    
  ckan:
      build: .
      ports:
          - "5000:5000"
      environment:
        #- CKAN_INI=/usr/lib/who.ini      
        - WTF_CSRF_ENABLED=False
        - WTF_CSRF_CHECK_DEFAULT=True
        - OAUTHLIB_INSECURE_TRANSPORT=True
        - CKAN_SITE_URL=https://5000-maximilianopizar-ckan-t8tnyisyxsa.ws-us104.gitpod.io
        - CKAN_SOLR_URL=http://solr:8983/solr/ckan
        - CKAN_SQLALCHEMY_URL=postgresql://ckan:ckan@db/ckan
        - CKAN_REDIS_URL=redis://redis:6379/1
        - CKAN_OAUTH2_AUTHORIZATION_ENDPOINT=https://accounts.google.com/o/oauth2/auth
        - CKAN_OAUTH2_TOKEN_ENDPOINT=https://oauth2.googleapis.com/token
        - CKAN_OAUTH2_PROFILE_API_URL=https://oauth2.googleapis.com/oauth2/v1/userinfo
        - CKAN_OAUTH2_CLIENT_ID=client-id
        - CKAN_OAUTH2_CLIENT_SECRET=client-secret
        - CKAN_OAUTH2_SCOPE=https://oauth2.googleapis.com/oauth2/v1/userinfo.email https://oauth2.googleapis.com/oauth2/v1/userinfo.profile
        - CKAN_OAUTH2_PROFILE_API_USER_FIELD=email
        - CKAN_OAUTH2_PROFILE_API_FULLNAME_FIELD=name
        - CKAN_OAUTH2_AUTHORIZATION_HEADER=Authorization      
        - CKAN_OAUTH2_PROFILE_API_MAIL_FIELD=email
        - CKAN_OAUTH2_REMEMBER_NAME=fake
        - CKAN_OAUTH2_JWT_ENABLE=True
      volumes:
        - ./who.ini:/usr/lib/who.ini          
      depends_on:
          - solr          
      networks:
          - monolito               
  db:
    build:
      context: postgresql/
      args:
       - DATASTORE_READONLY_PASSWORD=datastore
       - POSTGRES_PASSWORD=ckan
    environment:
      - DATASTORE_READONLY_PASSWORD=datastore
      - POSTGRES_PASSWORD=ckan
      - PGDATA=/var/lib/postgresql/data/db
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ckan"]
    networks:
        - monolito       
  redis:
    image: redis:6
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-e", "QUIT"]     
    networks:
        - monolito        
  solr:
    image: ckan/ckan-solr:2.9-solr8
    volumes:
      - solr_data:/var/solr
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://localhost:8983/solr/"]
    depends_on:
        - db           
    networks:
        - monolito       

