FROM alpine:3.6

# MAINTENER is deprecated
LABEL maintainer="https://github.com/ckan/ckan"

# Variables for paster / .env
ARG CKAN_TEST_DOCKER
ENV CKAN_HOME=${CKAN_HOME:-/usr/lib/ckan} \
    CKAN_VENV=${CKAN_VENV:-$CKAN_HOME/venv} \
    CKAN_CONFIG=${CKAN_CONFIG:-/etc/ckan} \
    CKAN_STORAGE_PATH=${CKAN_STORAGE_PATH:-/var/lib/ckan} \
    CKAN_SITE_ID=${CKAN_SITE_ID:-default} \
    CKAN_SITE_URL=${CKAN_SITE_URL:-http://localhost:5000} \
    CKAN_SQLALCHEMY_URL=${CKAN_SQLALCHEMY_URL:-postgresql://ckan:ckan@db/ckan} \
    CKAN_SOLR_URL=${CKAN_SOLR_URL:-http://solr:8983/solr/ckan} \
    CKAN_REDIS_URL=${CKAN_REDIS_URL:-redis://redis:6379/1} \
    CKAN_STORAGE_PATH=${CKAN_STORAGE_PATH:-/var/lib/ckan} \
    CKAN_DATAPUSHER_URL=${CKAN_DATAPUSHER_URL:-http://datapusher:8800} \
    CKAN_DATASTORE_WRITE_URL=${CKAN_DATASTORE_WRITE_URL:-postgresql://ckan:ckan@db/datastore} \
    CKAN_DATASTORE_READ_URL=${CKAN_DATASTORE_READ_URL:-postgresql://datastore_ro:datastore@db/datastore} \
    CKAN_VERSION=${CKAN_VERSION:-2.7.2} \
    CKAN_TEST_DOCKER=${CKAN_TEST_DOCKER:-false}


COPY contrib/docker/ckan-entrypoint.sh /ckan-entrypoint.sh

# paster requires py2-pip
RUN set -ex && \
    apk add --no-cache python2 libpq libstdc++ libmagic \
         py2-pip postgresql-client libffi && \ 
    apk add --no-cache --virtual .build-run-testing \ 
        --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing \
        geos py-geos && \ 
    apk add --no-cache  \
        --virtual=.build-dependencies \
        libxslt-dev libxml2-dev libressl2.5-libssl libffi-dev postgresql-dev \
        g++ musl-dev git libffi-dev \
        python2-dev openssl ca-certificates && \
    apk add --no-cache --virtual .build-deps-testing \ 
        --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing \
        geos-dev && \
    find /usr/lib/python2.*/ -name 'tests' -exec rm -r '{}' + && \
    mkdir -p /usr/lib/ckan/venv/src/ckan /etc/ckan /var/lib/ckan && \
    wget https://raw.githubusercontent.com/ckan/ckan/ckan-"$CKAN_VERSION"/requirements.txt && \
    pip install --no-cache-dir -r requirements.txt && \
    pip install -e 'git+https://github.com/ckan/ckan.git@ckan-'"$CKAN_VERSION"'#egg=ckan' && \
    wget https://raw.githubusercontent.com/ckan/ckan/ckan-"$CKAN_VERSION"/ckan/config/who.ini -O /etc/ckan/who.ini && \
    chmod +x /ckan-entrypoint.sh && \
    sed -i -e 's/ckan-paster/paster/g' ckan-entrypoint.sh
  #  apk del --purge .build-dependencies .build-deps-testing

RUN paster make-config --no-interactive ckan /etc/ckan/ckan.ini 

EXPOSE 5000
ENTRYPOINT ["/ckan-entrypoint.sh"]
CMD ["paster","serve","/etc/ckan/ckan.ini"]
