Overview
--------

The |site| data catalog is not only available in a web browser, but also
via its Application Programming Interface (API).

The |api| can be used |usage| the catalog. This document describes the 
resource locations, data formats, and status codes which comprise the |site|
|api|, so that anyone can create software applications that use the |api|
service.

The |site| |api| follows the RESTful (Representational State 
Transfer) style. Resource locations are separated both from the methods
supported by the resources, and from the data formats and status codes
used by the methods.

