Search Formats
~~~~~~~~~~~~~~

Here are the data formats for the Search API.

.. include:: search_formats_table.rst.inc

The ``Package`` and ``Revision`` data formats are as defined in `Model Formats`_.

**Package Parameters**

.. include:: search/package_params_table.rst.inc

**Resource Parameters**

.. include:: search/resource_params_table.rst.inc

**Revision Parameters**

.. include:: search/revision_params_table.rst.inc

