VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Define a Vagrant VM (Linux host) for Docker
  config.vm.define "dockerHost" do |host|
    host.vm.box = "hashicorp/precise64"
    host.vm.provision "docker"
    # disable SSH
    host.vm.provision "shell", inline:
      "ps aux | grep 'sshd:' | awk '{print $2}' | xargs kill"
    # forward ports as required
    host.vm.network "forwarded_port",
      guest: 80, host: 8080, auto_correct: true
    host.vm.network "forwarded_port",
      guest: 8983, host: 8983, auto_correct: true
    host.vm.network "forwarded_port",
      guest: 5432, host: 5432, auto_correct: true
  end

end
