Search Resources
~~~~~~~~~~~~~~~~

Here are the published resources of the Search API.

+---------------------------+--------------------------+
| Resource                  | Location                 |
+===========================+==========================+
| Package Search            | ``/api/search/package``  |
+---------------------------+--------------------------+
| Resource Search           | ``/api/search/resource`` |
+---------------------------+--------------------------+
| Revision Search           | ``/api/search/revision`` |
+---------------------------+--------------------------+
| Tag Counts                | ``/api/tag_counts``      |
+---------------------------+--------------------------+

See below for more information about package and revision search parameters.

