---

- name: 'Provision {{ application_name }} staging'
  hosts: iod-ckan-live
  gather_facts: no
  become: true

  vars:
    - deploy_env: staging
    - ckan_site_url: http://iod-ckan-live.aws.smallmedia.org.uk/
    - datapusher_tgz: https://github.com/ckan/datapusher/archive/0.0.10.tar.gz
    - datapusher_root: /usr/lib/ckan/datapusher
    - git_branch: iod-v2.6
    - application_name: 'iod-ckan'
    - set_up_application_user: yes
    - application_user: 'iod-ckan'
    - application_group: webapps
    - update_apt_cache: yes
    - django_settings_file: 'app.core.settings.staging'
    - requirements_file: '{{ git_root }}/requirements.txt'
    - virtualenv_path: '/webapps/{{ application_name }}'
    - django_dir: "{{ git_root }}" #  Location of manage.py
    - run_django_collectstatic: yes

  vars_files:
    - vault/secrets.yml
    - vars/db_live.yml
    - vars/web.yml

  roles:
    - base
    - ckan-deps
    - web
