---

- name: 'Provision {{ application_name }} staging'
  hosts: staging
  gather_facts: no
  become: true

  vars:
    - deploy_env: staging
    - git_branch: master
    - application_name: ''
    - set_up_application_user: yes
    - application_user: ''
    - application_group: webapps
    - update_apt_cache: yes
    - django_settings_file: 'app.core.settings.staging'
    - requirements_file: '{{ git_root }}/requirements.txt'
    - virtualenv_path: '/webapps/{{ application_name }}'
    - django_dir: "{{ git_root }}" #  Location of manage.py
    - run_django_collectstatic: yes
    - js_directory: '{{ django_dir }}'

  vars_files:
    - vault/secrets.yml
    - vars/db.yml
    - vars/web.yml

  roles:
    - base
    - db
    - web
    - nodejs
