Form Resources
~~~~~~~~~~~~~~

Here are the resources of the Form API.

+--------------------------------+-------------------------------------------------------------------+
| Resource                       | Location                                                          |
+================================+===================================================================+
| Package Edit Form              | ``/api/form/package/edit/PACKAGE-REF``                            |
+--------------------------------+-------------------------------------------------------------------+

Possible values for PACKAGE-REF are the package id, or the current package name.



