FROM solr:latest
MAINTAINER Open Knowledge

# Envrioment Variables
ENV SOLR_HOME /opt/solr

# Schema
ADD https://raw.githubusercontent.com/ckan/ckan/master/ckan/config/solr/schema.xml $SOLR_HOME/solr.xml