Search Formats
~~~~~~~~~~~~~~

Here are the data formats for the Search API.

.. include:: formats_table.rst.inc

The ``Package`` and ``Revision`` data formats are as defined in `Model Formats`_.

**Package Parameters**

.. include:: package_params_table.rst.inc

**Resource Parameters**

.. include:: resource_params_table.rst.inc

**Revision Parameters**

.. include:: revision_params_table.rst.inc

