#!/bin/sh

# URL for the primary database, in the format expected by sqlalchemy (required
# unless linked to a container called 'db')
: ${DATABASE_URL:=}
# URL for solr (required unless linked to a container called 'solr')
: ${SOLR_URL:=}
# Email to which errors should be sent (optional, default: none)
: ${ERROR_EMAIL:=}

set -eu

CONFIG="${CKAN_CONFIG}/ckan.ini"

abort () {
  echo "$@" >&2
  exit 1
}

write_config () {
  "$CKAN_HOME"/bin/paster make-config ckan "$CONFIG"

  "$CKAN_HOME"/bin/paster --plugin=ckan config-tool "$CONFIG" -e \
      "sqlalchemy.url = ${DATABASE_URL}" \
      "solr_url = ${SOLR_URL}" \
      "ckan.site_url = $(hostname -f)" \
      "ckan.datapusher.url = http://$(hostname -f):8800" \
      "ckan.storage_path = /var/lib/ckan" \
      "email_to = clementmouchet@gmail.com" \
      "error_email_from = ckan@$(hostname -f)" \
      "ckan.datastore.write_url = ${DATASTORE_WRITE_URL}" \
      "ckan.datastore.read_url = ${DATASTORE_READ_URL}" \
      "ckan.plugins = datastore datapusher resource_proxy stats text_view recline_view pdf_view viewhelpers linechart barchart piechart basicgrid dashboard_preview navigablemap choroplethmap"

  if [ -n "$ERROR_EMAIL" ]; then
    sed -i -e "s&^#email_to.*&email_to = ${ERROR_EMAIL}&" "$CONFIG"
  fi
}

link_postgres_url () {
  local user=$POSTGRESQL_USER
  local pass=$POSTGRESQL_PASS
  local db=$POSTGRESQL_DB
  local host=$DB_PORT_5432_TCP_ADDR
  local port=$DB_PORT_5432_TCP_PORT
  echo "postgresql://${user}:${pass}@${host}:${port}/${db}"
}

link_datastore_write_url () {
  local user=$POSTGRESQL_USER
  local pass=$POSTGRESQL_PASS
  local db=$POSTGRESQL_DATASTORE_DB
  local host=$DB_PORT_5432_TCP_ADDR
  local port=$DB_PORT_5432_TCP_PORT
  echo "postgresql://${user}:${pass}@${host}:${port}/${db}"
}

link_datastore_read_url () {
  local user=$POSTGRESQL_DATASTORE_USER
  local pass=$POSTGRESQL_DATASTORE_PASS
  local db=$POSTGRESQL_DATASTORE_DB
  local host=$DB_PORT_5432_TCP_ADDR
  local port=$DB_PORT_5432_TCP_PORT
  echo "postgresql://${user}:${pass}@${host}:${port}/${db}"
}

link_solr_url () {
  local host=$SOLR_PORT_8983_TCP_ADDR
  local port=$SOLR_PORT_8983_TCP_PORT
  echo "http://${host}:${port}/solr/ckan"
}

# If we don't already have a config file, bootstrap
if [ ! -e "$CONFIG" ]; then
  if [ -z "$DATABASE_URL" ]; then
    if ! DATABASE_URL=$(link_postgres_url); then
      abort "no DATABASE_URL specified and linked container called 'db' was not found"
    fi
    if ! DATASTORE_WRITE_URL=$(link_datastore_write_url); then
      abort "no DATASTORE_WRITE_URL specified and linked container called 'db' was not found"
    fi
    if ! DATASTORE_READ_URL=$(link_datastore_read_url); then
      abort "no DATASTORE_READ_URL specified and linked container called 'db' was not found"
    fi
  fi
  if [ -z "$SOLR_URL" ]; then
    if ! SOLR_URL=$(link_solr_url); then
      abort "no SOLR_URL specified and linked container called 'solr' was not found"
    fi
  fi
  write_config
fi
