#!/bin/sh
exec 2>&1

# Number of gunicorn workers to spawn (optional, default: 2)
: ${GUNICORN_NUM_WORKERS:=2}

set -eu

exec "$CKAN_HOME"/bin/gunicorn \
  -b unix:/var/run/gunicorn-ckan.sock \
  -n "$GUNICORN_NUM_WORKERS" \
  -k gevent \
  --max-requests 1000 \
  --paste "$CKAN_CONFIG"/ckan.ini
