#!/bin/sh
exec 2>&1

# URL for the primary database, in the format expected by sqlalchemy (required)
: ${DATABASE_URL:-}
# URL for solr (required)
: ${SOLR_URL:-}
# Email to which errors should be sent (optional, default: none)
: ${ERROR_EMAIL:-}

set -e

CONFIG="${CKAN_CONFIG}/ckan.ini"

abort () {
  echo "$@" >&2
  exit 1
}

bootstrap () {
  "$CKAN_HOME"/bin/paster make-config ckan "$CONFIG"

  sed -i \
      -e "s&^sqlalchemy\.url =.*&sqlalchemy.url = ${DATABASE_URL}&" \
      -e "s&^#solr_url.*&solr_url = ${SOLR_URL}&" \
      -e "s&^#ckan.storage_path.*&ckan.storage_path = /var/lib/ckan&" \
      -e "s&^email_to.*&#email_to = disabled@example.com&" \
      -e "s&^error_email_from.*&error_email_from = ckan@$(hostname -f)&" \
      "${CONFIG}"

  if [ -n "$ERROR_EMAIL" ]; then
    sed -i -e "s&^#email_to.*&email_to = ${ERROR_EMAIL}&" "$CONFIG"
  fi

  cd "$CKAN_HOME"/src/ckan && "$CKAN_HOME"/bin/paster db init -c "$CONFIG"
}

# If we don't already have a config file, bootstrap
if [ ! -e "$CONFIG" ]; then
  if [ -z "$DATABASE_URL" ]; then
    abort "no DATABASE_URL specified"
  fi
  if [ -z "$SOLR_URL" ]; then
    abort "no SOLR_URL specified"
  fi
  bootstrap
fi

. /etc/apache2/envvars
exec /usr/sbin/apache2 -D FOREGROUND
