---


- name: Install cKan OS deps
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - build-essential
    - git
    - git-core
    - libpq-dev
    - libxml2-dev
    - libxslt1-dev
    - openjdk-6-jdk
    - python-dev
    - python-pip
    - python-virtualenv
    - redis-server
    - solr-jetty
    - zlib1g-dev


- name: Install Jetty config file
  template:
    dest: /etc/default/jetty
    src: jetty.j2


- name: Install Solr schema
  file:
    path: /etc/solr/conf/schema.xml
    src: "{{ django_dir }}/ckan/config/solr/schema.xml"
    state: link
    force: true


- name: Start/enable jetty
  service:
    name: jetty
    enabled: true
    state: restarted


- name: Install ckan dir exists
  file:
    path: "{{item}}"
    state: directory
  with_items:
  - /etc/ckan
  - /etc/ckan/default


- name: Install cKan paster config file
  template:
    dest: /etc/ckan/default/ckan.ini
    src: ckan.ini.j2
