---


- name: Install cKan OS deps
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - python-dev
    - libpq-dev
    - python-pip
    - python-virtualenv
    - git-core
    - solr-jetty
    - openjdk-6-jdk
    - redis-server


- name: Install Jetty config file
  template:
    dest: /etc/default/jetty
    src: jetty.j2


- name: Install Solr schema
  file:
    path: /etc/solr/conf/schema.xml
    src: "{{ git_root }}/ckan/config/solr/schema.xml"
    state: link
    force: true


- name: Start/enable jetty
  service:
    name: jetty
    enabled: true
    state: restarted


- name: Install cKan paster config file
  template:
    dest: /etc/ckan/default/ckan.ini
    src: ckan.ini.j2
