name: Cypress
on:
#  pull_request:
  workflow_call:
  workflow_dispatch:
env:
  NODE_VERSION: '16'
  PYTHON_VERSION: '3.10'

permissions: {}

jobs:
  cypress:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    services:
      ckan_postgres:
        image: postgres:15
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: ckan_default
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: ckan_test

      ckan_redis:
        image: redis:7
        ports:
          - 6379:6379
      ckan_solr:
        image: ckan/ckan-solr:master
        ports:
          - 8983:8983

    env:
      CKAN_SQLALCHEMY_URL: postgresql://ckan_default:pass@localhost/ckan_test
      CKAN_SOLR_URL: http://localhost:8983/solr/ckan
      CKAN_REDIS_URL: redis://localhost:6379/1

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install python deps
        run: |
         pip install -U pip
         pip install -r requirements.txt -r dev-requirements.txt -e.
         pip check

      - name: Init environment
        run: |
          ckan -c test-core-ci.ini db init
          #cypress testing requires activity plugin to be active
          ckan config-tool test-core-ci.ini "ckan.plugins = activity"

      - name: Run Cypress
        uses: cypress-io/github-action@dace029018fcdf86e0df89a31bc3cfa5b32570d8 # v7.3.0
        with:
          start: ckan -c test-core-ci.ini run

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore
