name: Docs
on:
  workflow_call:
  workflow_dispatch:
env:
  PYTHON_VERSION: '3.10'

permissions: {}

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0  # Fetch all history, including tags
          persist-credentials: false

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install python deps
        run: |
         pip install -U pip
         pip install -r requirements.txt -r dev-requirements.txt -e .
         pip check

      - name: Create Docs
        run: |
           sphinx-build doc build/sphinx
