name: Publish to TestPyPI

# Publish to Test PyPI when a pull request is merged to master
on:
  push:
    branches:
      - 'master'

jobs:
  build:
    if: github.repository == 'ckan/ckan'
    name: Build distribution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"
    - name: Add timestamp to version number
      run: |
        TIMESTAMP=$(date +"%Y%m%d%H%M")
        sed -E -i 's/__version__ = "(.*)"$/__version__ = "\1.post'$TIMESTAMP'"/' ckan/__init__.py
    - name: Install pypa/build
      run: >-
        python3 -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: python3 -m build
    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

  publish-to-testpypi:
    name: Publish Python distribution on TestPyPI
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: test-pypi
      url: https://test.pypi.org/p/ckan
    permissions:
      id-token: write
    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/

  publishSkipped:
    if: github.repository != 'ckan/ckan'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "## Skipping PyPI publish on downstream repository" >> $GITHUB_STEP_SUMMARY
