name: Changelog entries
on: [pull_request]

permissions: {}

jobs:
  towncrier:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'No changelog') }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install python deps
        run: pip install -r requirements.txt -r dev-requirements.txt -e.

      - name: Check that changelog is updated
        run: towncrier check >> $GITHUB_STEP_SUMMARY
